name             'packagecloud'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
version          '2.0.6'
source_url       'https://github.com/sous-chefs/packagecloud'
issues_url       'https://github.com/sous-chefs/packagecloud/issues'
description      'Installs/Configures packagecloud.io repositories.'
chef_version     '>= 15.3'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
