name             'packagecloud'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures packagecloud.io repositories.'
version           '1.0.1'
source_url        'https://github.com/sous-chefs/packagecloud-cookbook'
issues_url        'https://github.com/sous-chefs/packagecloud-cookbook/issues'
chef_version      '>= 15.3'

supports 'ubuntu'
supports 'debian'
supports 'redhat'
supports 'centos'
supports 'amazon'
supports 'oracle'
supports 'fedora'
supports 'scientific'
